[Server]
Mode = "debug"
IP = "0.0.0.0"
Port = "5000"
#LogPath = "./logs"
GRPCPort = 50052


[MySQL]
DBName = "jobor"
User = "xx"
Password = "xx"
Host = "xx"
Port = 3306
Parameters = "charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"


[Gorm]
Debug = false
DBType = "mysql"
TablePrefix = ""
MaxLifetime = 100
MaxOpenConn = 200
MaxIdleConn = 200

[Redis]
Host = "xxx:6379" # "xxxx:6379,xxxx:6379"
Password = ""
DB = 1

[JWT]
TokenType = "Bearer"     # Bearer
TokenKey = "jS2SnJdxxmTKRNQYh"
RefreshKey = "jreJdXxT0kenYh"
Age = 360000

[LDAP]
addr = "ad.example.org:389"
baseDn = "dc=example,dc=org"
bindDn = "manager@example.org"
bindPass = "password"
authFilter = "(&(sAMAccountName=%s))"
attributes = ["sAMAccountName", "displayName", "mail"]
tls = false
startTLS = false

[email]
smtpHost = "smtp.qq.com"
port = 465
username = "xx@qq.com"
password = "xx"
from = "xx@xx.com"
tls = false
anonymous = false
skipVerify = false